version: '3'
services:
  app:
    build: .
    ports:
      - '3000:8080'
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgresdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local